// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_build_sql_query_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: *mut u8,
    arg3: usize,
    arg4: i32,
    arg5: *mut u8,
    arg6: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let len1 = arg3;
    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
    let result3 = T::build_sql_query(
        _rt::string_lift(bytes0),
        _rt::string_lift(bytes1),
        match arg4 {
            0 => None,
            1 => {
                let e = {
                    let len2 = arg6;
                    let bytes2 = _rt::Vec::from_raw_parts(arg5.cast(), len2, len2);
                    _rt::string_lift(bytes2)
                };
                Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
        },
    );
    let ptr4 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result3 {
        Ok(e) => {
            *ptr4.add(0).cast::<u8>() = (0i32) as u8;
            let vec5 = (e.into_bytes()).into_boxed_slice();
            let ptr5 = vec5.as_ptr().cast::<u8>();
            let len5 = vec5.len();
            ::core::mem::forget(vec5);
            *ptr4.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
            *ptr4.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5
                .cast_mut();
        }
        Err(e) => {
            *ptr4.add(0).cast::<u8>() = (1i32) as u8;
            let vec6 = (e.into_bytes()).into_boxed_slice();
            let ptr6 = vec6.as_ptr().cast::<u8>();
            let len6 = vec6.len();
            ::core::mem::forget(vec6);
            *ptr4.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
            *ptr4.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr6
                .cast_mut();
        }
    };
    ptr4
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_build_sql_query<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
        _ => {
            let l3 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l4 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l3, l4, 1);
        }
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_hydrate_results_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: *mut u8,
    arg3: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let len1 = arg3;
    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
    let result2 = T::hydrate_results(_rt::string_lift(bytes0), _rt::string_lift(bytes1));
    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
    match result2 {
        Ok(e) => {
            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
            let vec4 = (e.into_bytes()).into_boxed_slice();
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();
            ::core::mem::forget(vec4);
            *ptr3.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
            *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4
                .cast_mut();
        }
        Err(e) => {
            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
            let vec5 = (e.into_bytes()).into_boxed_slice();
            let ptr5 = vec5.as_ptr().cast::<u8>();
            let len5 = vec5.len();
            ::core::mem::forget(vec5);
            *ptr3.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
            *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5
                .cast_mut();
        }
    };
    ptr3
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_hydrate_results<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(0).cast::<u8>());
    match l0 {
        0 => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
        }
        _ => {
            let l3 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l4 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l3, l4, 1);
        }
    }
}
pub trait Guest {
    fn build_sql_query(
        query: _rt::String,
        metadata_json: _rt::String,
        options_json: Option<_rt::String>,
    ) -> Result<_rt::String, _rt::String>;
    fn hydrate_results(
        rows_json: _rt::String,
        metadata_json: _rt::String,
    ) -> Result<_rt::String, _rt::String>;
}
#[doc(hidden)]
macro_rules! __export_world_super_join_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "build-sql-query")] unsafe extern "C" fn
        export_build_sql_query(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8, arg3 :
        usize, arg4 : i32, arg5 : * mut u8, arg6 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_build_sql_query_cabi::<$ty > (arg0, arg1, arg2,
        arg3, arg4, arg5, arg6) } } #[unsafe (export_name = "cabi_post_build-sql-query")]
        unsafe extern "C" fn _post_return_build_sql_query(arg0 : * mut u8,) { unsafe {
        $($path_to_types)*:: __post_return_build_sql_query::<$ty > (arg0) } } #[unsafe
        (export_name = "hydrate-results")] unsafe extern "C" fn
        export_hydrate_results(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8, arg3 :
        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
        _export_hydrate_results_cabi::<$ty > (arg0, arg1, arg2, arg3) } } #[unsafe
        (export_name = "cabi_post_hydrate-results")] unsafe extern "C" fn
        _post_return_hydrate_results(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_hydrate_results::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_super_join_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 3 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 3 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_super_join_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_super_join_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_super_join_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:super-join:core:super-join:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 287] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x9e\x01\x01A\x02\x01\
A\x06\x01ks\x01j\x01s\x01s\x01@\x03\x05querys\x0dmetadata-jsons\x0coptions-json\0\
\0\x01\x04\0\x0fbuild-sql-query\x01\x02\x01@\x02\x09rows-jsons\x0dmetadata-jsons\
\0\x01\x04\0\x0fhydrate-results\x01\x03\x04\0\x1asuper-join:core/super-join\x04\0\
\x0b\x10\x01\0\x0asuper-join\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0d\
wit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
