// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type RootInput = super_join::graphql::super_join::RootInput;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_build_sql_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: *mut u8,
    arg3: usize,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let base64 = arg2;
    let len64 = arg3;
    let mut result64 = _rt::Vec::with_capacity(len64);
    for i in 0..len64 {
        let base = base64.add(i * (8 * ::core::mem::size_of::<*const u8>()));
        let e64 = {
            let l1 = *base.add(0).cast::<*mut u8>();
            let l2 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len3 = l2;
            let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
            let l4 = *base
                .add(2 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l5 = *base.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len6 = l5;
            let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
            let l7 = *base
                .add(4 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l8 = *base.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len9 = l8;
            let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
            let l10 = *base
                .add(6 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l11 = *base.add(7 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base63 = l10;
            let len63 = l11;
            let mut result63 = _rt::Vec::with_capacity(len63);
            for i in 0..len63 {
                let base = base63
                    .add(i * (8 + 34 * ::core::mem::size_of::<*const u8>()));
                let e63 = {
                    let l12 = *base.add(0).cast::<*mut u8>();
                    let l13 = *base
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len14 = l13;
                    let bytes14 = _rt::Vec::from_raw_parts(l12.cast(), len14, len14);
                    let l15 = *base
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l16 = *base
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len17 = l16;
                    let bytes17 = _rt::Vec::from_raw_parts(l15.cast(), len17, len17);
                    let l18 = *base
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l19 = *base
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len20 = l19;
                    let bytes20 = _rt::Vec::from_raw_parts(l18.cast(), len20, len20);
                    let l21 = *base
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l22 = *base
                        .add(7 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len23 = l22;
                    let bytes23 = _rt::Vec::from_raw_parts(l21.cast(), len23, len23);
                    let l24 = *base
                        .add(8 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l25 = *base
                        .add(9 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len26 = l25;
                    let bytes26 = _rt::Vec::from_raw_parts(l24.cast(), len26, len26);
                    let l27 = *base
                        .add(10 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l28 = *base
                        .add(11 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len29 = l28;
                    let bytes29 = _rt::Vec::from_raw_parts(l27.cast(), len29, len29);
                    let l30 = *base
                        .add(12 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l31 = *base
                        .add(13 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len32 = l31;
                    let bytes32 = _rt::Vec::from_raw_parts(l30.cast(), len32, len32);
                    let l33 = *base
                        .add(14 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l34 = *base
                        .add(15 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len35 = l34;
                    let bytes35 = _rt::Vec::from_raw_parts(l33.cast(), len35, len35);
                    let l36 = *base
                        .add(16 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l37 = *base
                        .add(17 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len38 = l37;
                    let bytes38 = _rt::Vec::from_raw_parts(l36.cast(), len38, len38);
                    let l39 = i32::from(
                        *base.add(18 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    let l40 = *base
                        .add(19 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l41 = *base
                        .add(20 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len42 = l41;
                    let bytes42 = _rt::Vec::from_raw_parts(l40.cast(), len42, len42);
                    let l43 = *base
                        .add(21 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l44 = *base
                        .add(22 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len45 = l44;
                    let bytes45 = _rt::Vec::from_raw_parts(l43.cast(), len45, len45);
                    let l46 = *base
                        .add(23 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l47 = *base
                        .add(24 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len48 = l47;
                    let bytes48 = _rt::Vec::from_raw_parts(l46.cast(), len48, len48);
                    let l49 = *base
                        .add(25 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l50 = *base
                        .add(26 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len51 = l50;
                    let bytes51 = _rt::Vec::from_raw_parts(l49.cast(), len51, len51);
                    let l52 = *base
                        .add(27 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l53 = *base
                        .add(28 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len54 = l53;
                    let bytes54 = _rt::Vec::from_raw_parts(l52.cast(), len54, len54);
                    let l55 = *base
                        .add(29 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l56 = *base
                        .add(30 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len57 = l56;
                    let bytes57 = _rt::Vec::from_raw_parts(l55.cast(), len57, len57);
                    let l58 = *base
                        .add(31 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l59 = *base
                        .add(32 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len60 = l59;
                    let bytes60 = _rt::Vec::from_raw_parts(l58.cast(), len60, len60);
                    let l61 = i32::from(
                        *base.add(33 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    let l62 = *base
                        .add(34 * ::core::mem::size_of::<*const u8>())
                        .cast::<i64>();
                    super_join::graphql::super_join::Field {
                        column: super_join::graphql::super_join::Column {
                            column: _rt::string_lift(bytes14),
                            table: _rt::string_lift(bytes17),
                            alias: _rt::string_lift(bytes20),
                        },
                        join: super_join::graphql::super_join::Join {
                            on: super_join::graphql::super_join::SqlExpr {
                                column: super_join::graphql::super_join::Column {
                                    column: _rt::string_lift(bytes23),
                                    table: _rt::string_lift(bytes26),
                                    alias: _rt::string_lift(bytes29),
                                },
                                param: super_join::graphql::super_join::Param {
                                    param: _rt::string_lift(bytes32),
                                },
                                literal: super_join::graphql::super_join::Literal {
                                    literal: _rt::string_lift(bytes35),
                                },
                                raw: _rt::string_lift(bytes38),
                            },
                            kind: super_join::graphql::super_join::JoinType::_lift(
                                l39 as u8,
                            ),
                        },
                        where_: _rt::string_lift(bytes42),
                        order_by: super_join::graphql::super_join::OrderBy {
                            expr: super_join::graphql::super_join::SqlExpr {
                                column: super_join::graphql::super_join::Column {
                                    column: _rt::string_lift(bytes45),
                                    table: _rt::string_lift(bytes48),
                                    alias: _rt::string_lift(bytes51),
                                },
                                param: super_join::graphql::super_join::Param {
                                    param: _rt::string_lift(bytes54),
                                },
                                literal: super_join::graphql::super_join::Literal {
                                    literal: _rt::string_lift(bytes57),
                                },
                                raw: _rt::string_lift(bytes60),
                            },
                            direction: super_join::graphql::super_join::SqlOrderDirection::_lift(
                                l61 as u8,
                            ),
                        },
                        limit: l62 as u64,
                    }
                };
                result63.push(e63);
            }
            _rt::cabi_dealloc(
                base63,
                len63 * (8 + 34 * ::core::mem::size_of::<*const u8>()),
                8,
            );
            super_join::graphql::super_join::Node {
                alias: _rt::string_lift(bytes3),
                field_name: _rt::string_lift(bytes6),
                table: _rt::string_lift(bytes9),
                fields: result63,
            }
        };
        result64.push(e64);
    }
    _rt::cabi_dealloc(
        base64,
        len64 * (8 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let result65 = T::build_sql(_rt::string_lift(bytes0), result64);
    let ptr66 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec67 = (result65.into_bytes()).into_boxed_slice();
    let ptr67 = vec67.as_ptr().cast::<u8>();
    let len67 = vec67.len();
    ::core::mem::forget(vec67);
    *ptr66.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len67;
    *ptr66.add(0).cast::<*mut u8>() = ptr67.cast_mut();
    ptr66
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_build_sql<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
pub trait Guest {
    fn build_sql(query: _rt::String, root: RootInput) -> _rt::String;
}
#[doc(hidden)]
macro_rules! __export_world_graphql_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "build-sql")] unsafe extern "C" fn
        export_build_sql(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8, arg3 : usize,)
        -> * mut u8 { unsafe { $($path_to_types)*:: _export_build_sql_cabi::<$ty > (arg0,
        arg1, arg2, arg3) } } #[unsafe (export_name = "cabi_post_build-sql")] unsafe
        extern "C" fn _post_return_build_sql(arg0 : * mut u8,) { unsafe {
        $($path_to_types)*:: __post_return_build_sql::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_graphql_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod super_join {
    pub mod graphql {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod super_join {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct Column {
                pub column: _rt::String,
                pub table: _rt::String,
                pub alias: _rt::String,
            }
            impl ::core::fmt::Debug for Column {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Column")
                        .field("column", &self.column)
                        .field("table", &self.table)
                        .field("alias", &self.alias)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct Param {
                pub param: _rt::String,
            }
            impl ::core::fmt::Debug for Param {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Param").field("param", &self.param).finish()
                }
            }
            #[derive(Clone)]
            pub struct Literal {
                pub literal: _rt::String,
            }
            impl ::core::fmt::Debug for Literal {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Literal").field("literal", &self.literal).finish()
                }
            }
            #[derive(Clone)]
            pub struct SqlExpr {
                pub column: Column,
                pub param: Param,
                pub literal: Literal,
                pub raw: _rt::String,
            }
            impl ::core::fmt::Debug for SqlExpr {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("SqlExpr")
                        .field("column", &self.column)
                        .field("param", &self.param)
                        .field("literal", &self.literal)
                        .field("raw", &self.raw)
                        .finish()
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum SqlOrderDirection {
                Asc,
                Desc,
            }
            impl ::core::fmt::Debug for SqlOrderDirection {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        SqlOrderDirection::Asc => {
                            f.debug_tuple("SqlOrderDirection::Asc").finish()
                        }
                        SqlOrderDirection::Desc => {
                            f.debug_tuple("SqlOrderDirection::Desc").finish()
                        }
                    }
                }
            }
            impl SqlOrderDirection {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> SqlOrderDirection {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => SqlOrderDirection::Asc,
                        1 => SqlOrderDirection::Desc,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Clone)]
            pub struct OrderBy {
                pub expr: SqlExpr,
                pub direction: SqlOrderDirection,
            }
            impl ::core::fmt::Debug for OrderBy {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("OrderBy")
                        .field("expr", &self.expr)
                        .field("direction", &self.direction)
                        .finish()
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum JoinType {
                Join,
                CrossJoin,
                InnerJoin,
                LeftJoin,
                RightJoin,
                FullOuterJoin,
            }
            impl ::core::fmt::Debug for JoinType {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        JoinType::Join => f.debug_tuple("JoinType::Join").finish(),
                        JoinType::CrossJoin => {
                            f.debug_tuple("JoinType::CrossJoin").finish()
                        }
                        JoinType::InnerJoin => {
                            f.debug_tuple("JoinType::InnerJoin").finish()
                        }
                        JoinType::LeftJoin => {
                            f.debug_tuple("JoinType::LeftJoin").finish()
                        }
                        JoinType::RightJoin => {
                            f.debug_tuple("JoinType::RightJoin").finish()
                        }
                        JoinType::FullOuterJoin => {
                            f.debug_tuple("JoinType::FullOuterJoin").finish()
                        }
                    }
                }
            }
            impl JoinType {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> JoinType {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => JoinType::Join,
                        1 => JoinType::CrossJoin,
                        2 => JoinType::InnerJoin,
                        3 => JoinType::LeftJoin,
                        4 => JoinType::RightJoin,
                        5 => JoinType::FullOuterJoin,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Clone)]
            pub struct Join {
                pub on: SqlExpr,
                pub kind: JoinType,
            }
            impl ::core::fmt::Debug for Join {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Join")
                        .field("on", &self.on)
                        .field("kind", &self.kind)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct Field {
                pub column: Column,
                pub join: Join,
                pub where_: _rt::String,
                pub order_by: OrderBy,
                pub limit: u64,
            }
            impl ::core::fmt::Debug for Field {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Field")
                        .field("column", &self.column)
                        .field("join", &self.join)
                        .field("where", &self.where_)
                        .field("order-by", &self.order_by)
                        .field("limit", &self.limit)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct Node {
                pub alias: _rt::String,
                pub field_name: _rt::String,
                pub table: _rt::String,
                pub fields: _rt::Vec<Field>,
            }
            impl ::core::fmt::Debug for Node {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Node")
                        .field("alias", &self.alias)
                        .field("field-name", &self.field_name)
                        .field("table", &self.table)
                        .field("fields", &self.fields)
                        .finish()
                }
            }
            pub type RootInput = _rt::Vec<Node>;
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_graphql_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_graphql_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_graphql_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:super-join:graphql:graphql:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 689] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xb3\x04\x01A\x02\x01\
A\x06\x01B\x17\x01r\x03\x06columns\x05tables\x05aliass\x04\0\x06column\x03\0\0\x01\
r\x01\x05params\x04\0\x05param\x03\0\x02\x01r\x01\x07literals\x04\0\x07literal\x03\
\0\x04\x01r\x04\x06column\x01\x05param\x03\x07literal\x05\x03raws\x04\0\x08sql-e\
xpr\x03\0\x06\x01m\x02\x03asc\x04desc\x04\0\x13sql-order-direction\x03\0\x08\x01\
r\x02\x04expr\x07\x09direction\x09\x04\0\x08order-by\x03\0\x0a\x01m\x06\x04join\x0a\
cross-join\x0ainner-join\x09left-join\x0aright-join\x0ffull-outer-join\x04\0\x09\
join-type\x03\0\x0c\x01r\x02\x02on\x07\x04kind\x0d\x04\0\x04join\x03\0\x0e\x01r\x05\
\x06column\x01\x04join\x0f\x05wheres\x08order-by\x0b\x05limitw\x04\0\x05field\x03\
\0\x10\x01p\x11\x01r\x04\x05aliass\x0afield-names\x05tables\x06fields\x12\x04\0\x04\
node\x03\0\x13\x01p\x14\x04\0\x0aroot-input\x03\0\x15\x03\0\x1dsuper-join:graphq\
l/super-join\x05\0\x02\x03\0\0\x0aroot-input\x03\0\x0aroot-input\x03\0\x01\x01@\x02\
\x05querys\x04root\x02\0s\x04\0\x09build-sql\x01\x03\x04\0\x1asuper-join:graphql\
/graphql\x04\0\x0b\x0d\x01\0\x07graphql\x03\0\0\0G\x09producers\x01\x0cprocessed\
-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
